#!/usr/bin/perl

my $title = `head -1 $ARGV[0]`;
my $date = `TZ=gmt date +"%a, %d %b %Y %H:%M:%S GMT"`;
my $document = $ARGV[0];
$document =~ s/\.md$//;

chomp($title);
chomp($date);

print <<"ITEM";
    <item>
      <title>Musing #XXX: $title</title>
      <link>http://www.cs.grinnell.edu/~rebelsky/musings/$document</link>
      <guid>http://www.cs.grinnell.edu/~rebelsky/musings/$document</guid>
      <pubDate>$date</pubDate>
      <description>XXX.</description>
    </item>
ITEM

