#!/usr/bin/perl

# Usage: make-item FILE.md

# Extract basic information
my $file = $ARGV[0];
my $date = `TZ=gmt date +"%a, %d %b %Y %H:%M:%S GMT"`;
chomp($date);
my $title = `head -1 $file`;
chomp($title);
my $document = $file;
$document =~ s/\.md$//;


print <<"ITEM";
    <item>
      <title>Musing #XXX: $title</title>
      <link>https://www.cs.grinnell.edu/~rebelsky/musings/$document</link>
      <guid>https://www.cs.grinnell.edu/~rebelsky/musings/$document</guid>
      <pubDate>$date</pubDate>
      <description>XXX.</description>
    </item>
ITEM

